# Generated by Django 4.0.4 on 2022-06-04 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectif_classe', models.IntegerField(verbose_name='Effectif')),
                ('nom_classe', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_filiere', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_niveau', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salle', models.CharField(blank=True, max_length=50)),
                ('capacite_salle', models.IntegerField(verbose_name='capacite')),
            ],
        ),
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ue', models.CharField(max_length=40)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_specialite', models.CharField(max_length=30)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.classes')),
            ],
        ),
        migrations.CreateModel(
            name='EmploiDeTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_emploi', models.CharField(blank=True, max_length=60)),
                ('classe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emploi.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(blank=True, choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], default='Lundi', max_length=20)),
                ('heure', models.CharField(blank=True, choices=[('7h-9h55', '7h-9h55'), ('10h05-12h55', '10h05-12h55'), ('13h05-15h55', '13h05-15h55'), ('16h05-18h55', '16h05-18h55'), ('19h05-21h55', '19h05-21h55')], default='7h-9h55', max_length=12)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.classes')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.groupe')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.salle')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.uniteenseignement')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.filiere'),
        ),
        migrations.AddField(
            model_name='classes',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.niveau'),
        ),
    ]
