# Generated by Django 4.0.1 on 2022-06-07 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniteenseignement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
