# Generated by Django 4.0.4 on 2022-06-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='nom_classe',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
