# Generated by Django 4.0.4 on 2022-06-03 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ue', models.CharField(max_length=40)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.enseignant')),
            ],
        ),
        migrations.AlterField(
            model_name='cours',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.uniteenseignement'),
        ),
        migrations.DeleteModel(
            name='UniteEneseignement',
        ),
    ]
