# Generated by Django 4.0.4 on 2022-06-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emploidetemps',
            old_name='classe',
            new_name='classes',
        ),
    ]
