# Generated by Django 4.0.1 on 2022-06-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniteenseignement',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emploi.classe'),
        ),
    ]
