# Generated by Django 4.0.4 on 2022-06-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0002_classe_nom_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='jour',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=20),
        ),
    ]
