# Generated by Django 4.0.4 on 2022-06-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0002_alter_uniteenseignement_intitule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniteenseignement',
            name='intitule',
        ),
    ]
