# Generated by Django 4.0.4 on 2022-06-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0002_rename_classe_emploidetemps_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emploidetemps',
            old_name='classes',
            new_name='classe',
        ),
    ]
