# Generated by Django 4.0.4 on 2022-06-03 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0002_uniteenseignement_alter_cours_ue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='Salle',
            new_name='salle',
        ),
        migrations.AlterField(
            model_name='specialite',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.classes'),
        ),
    ]
