# Generated by Django 4.0.1 on 2022-06-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0002_alter_uniteenseignement_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='classe',
        ),
    ]
