# Generated by Django 4.0.4 on 2022-06-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0003_remove_uniteenseignement_intitule'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniteenseignement',
            name='intitule',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
