# Generated by Django 4.0.4 on 2022-06-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0003_rename_salle_cours_salle_alter_specialite_enseignant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialite',
            old_name='enseignant',
            new_name='classe',
        ),
    ]
