# Generated by Django 4.0.4 on 2022-06-05 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0003_rename_classes_emploidetemps_classe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmploiDeTemps',
        ),
    ]
