# Generated by Django 4.0.4 on 2022-06-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0004_rename_enseignant_specialite_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='heure',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='cours',
            name='jour',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='salle',
            name='nom_salle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
