# Generated by Django 4.0.4 on 2022-06-08 01:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0006_alter_cours_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='groupe',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('G4', 'G4')], max_length=11),
        ),
    ]
