# Generated by Django 4.0.4 on 2022-06-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0007_alter_cours_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniteenseignement',
            name='intitule',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
