# Generated by Django 4.0.4 on 2022-06-08 05:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0009_alter_uniteenseignement_intitule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='groupe',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('G4', 'G4')], max_length=11),
        ),
    ]
